#! /usr/bin/env bash

file=$1
filename="${file%.*}"
extension="${file##*.}"

case $extension in
    pdf )
        if [[ -z $2 ]]; then
            level=prepress
        else
            level=$2
        fi
        ps2pdf -dPDFSETTINGS=/$level "$file" "$filename""_compressed.""$extension"
        mv "$filename""_compressed.""$extension" "$file"
        ;;
    jpg|jpeg )
        jpegoptim "$file"
        ;;
    png )
        optipng "$file"
        ;;
esac
