#! /usr/bin/env bash

if [[ $1 == "f" ]];
then
    cp ~/Pictures/cache/* ~/Pictures/图片cache/
else
    cp ~/Pictures/cache/* ~/Pictures/图片/
    cp ~/Pictures/图片cache/* ~/Pictures/图片/
    rm ~/Pictures/图片cache/*
fi
