#! /usr/bin/env bash

if [[ $1 == "f" ]];
then
    cp ~/Pictures/cache/wallpaper.jpg ~/Pictures/图片cache/
else
    cp ~/Pictures/cache/wallpaper.jpg ~/Pictures/图片/
    cp ~/Pictures/图片cache/* ~/Pictures/图片/
fi
