#! /usr/bin/env bash

# type 'crontab -e' in terminal and add a line: '*/5 * * * * ~/Desktop/Shell-Scripts/unsplash'
# learn more at http://youness.net/linux/set-random-wallpapers-unsplash-com-ubuntu
# learn more about unsplash api at https://source.unsplash.com/

WALLPAPERPATH=~/Pictures
RESOLUTION="1920x1080"
KEYWORDS="wallpaper"
wget -O $WALLPAPERPATH/wallpaper-temp.jpg https://source.unsplash.com/featured/$RESOLUTION/?$KEYWORDS
mv $WALLPAPERPATH/wallpaper-temp.jpg $WALLPAPERPATH/wallpaper.jpg
if [ ! -d $WALLPAPERPATH/cache ]; then
    mkdir $WALLPAPERPATH/cache
fi
rm $WALLPAPERPATH/cache/*
cp $WALLPAPERPATH/wallpaper.jpg $WALLPAPERPATH/cache/$(date +%Y-%m-%d_%h-%m-%S).jpg
